### ISSUE TITLE
Problem to forward an email with a black background

### ISSUE THREAD

**Issue by terdnester** [mayank-gokarna/testbyt#3]
Problem to forward an email with a black background

_Originally posted by @mayank-gokarna in https://github.com/mayank-gokarna/testbyt/issues/2#issuecomment-761767217_

**Comment by terdnester** [comment]
Warn of links not matching link text

**Comment by terdnester** [comment]
What I like to have is the option, ideally enabled by default, which after clicking such a link displays a dialog that briefly informs about the problem, shows both links (the link text and the actual URL) and allows choosing which one to open.
Optionally there could also be the option to remember the decision and not to show the dialog again.

**Comment by mayank-gokarna** [comment]
Need to  merge it with the master branch
